# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'

target 'Beaconizer(Business)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beaconizer(Business)

  target 'Beaconizer(Business)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Beaconizer(Business)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
